RATELIMIT_DEFAULT = '10 per minute'
RATELIMIT_STORAGE_URL = 'memory://'
MAX_CONTENT_LENGTH = 1000000
AUDIT_LOG_PATH = 'audit_log.json'
CONFIDENCE_WEIGHTS = {'llm_judgment': 0.4,
                      'stylometry': 0.25,
                      'perplexity': 0.35}

CONFIDENCE_THRESHOLDS = [
    (0.00, 0.15, 'Your text is Human written'),
    (0.15, 0.30, 'Most of Your text is Human Written'),
    (0.30, 0.42, 'Your text is Most Likely Human written, may include parts generated by AI'),
    (0.42, 0.50, 'Your text is Likely Human written, may include parts generated by AI'),
    (0.50, 0.70, 'Your text contains mixed signals, with some parts generated by AI'),
    (0.70, 0.80, 'Your text is Likely AI-generated'),
    (0.80, 0.90, 'Your text is Most Likely AI-generated'),
    (0.90, 0.97, 'Most of Your text is AI-Generated'),
    (0.97, 1.00, 'Your text is AI-Generated'),
    ]

LABEL_REASONING = {
    'Your text is Human written': 
    ("Our analysis found natural variation in word choice, "
     "sentence structure, and phrasing patterns typical of human writing. "
     "The text shows unexpected conceptual jumps and stylistic choices "
     "consistent with authentic human expression."),
    
    'Most of Your text is Human Written': 
    ("Our analysis detected predominantly human writing patterns. "
     "The text shows natural variation in word choice and sentence structure. "
     "There may be small sections that exhibit AI-like characteristics, "
     "but the overall content appears human-written."),
    
    'Your text is Most Likely Human written, may include parts generated by AI': 
    ("Our analysis suggests this is primarily human-authored work. "
     "However, we detected some sections with patterns more typical of AI-generated text. "
     "This could mean: You used AI tools to help with specific sections, "
     "some paragraphs were rewritten multiple times, or the text includes quoted or referenced material."),
    
    'Your text is Likely Human written, may include parts generated by AI': 
    ("Our analysis produced mixed signals. "
     "Some patterns suggest human authorship, while others align with AI-generated text. "
     "This is common when: You revised and rewrote sections multiple times, "
     "the text spans different topics or writing styles, or you used AI tools for research or brainstorming."),
    
    'Your text contains mixed signals, with some parts generated by AI': 
    ("Our analysis produced conflicting signals: "
     "Some patterns suggest human writing, other patterns align with AI-generated text, "
     "and the overall style makes classification difficult. "
     "This could indicate: A mix of human and AI-generated content, formal or technical writing "
     "that resembles AI patterns, or content in a style or genre we classify less reliably."),
    
    'Your text is Likely AI-generated': 
    ("We detected patterns consistent with AI-generated text, including: "
     "Formal structure and consistent phrasing typical of language models, "
     "low variation in sentence length and word choice, "
     "technical terminology arranged in predictable sequences, "
     "and statistical patterns matching AI baseline."),
    
    'Your text is Most Likely AI-generated': 
    ("Our analysis detected strong patterns across multiple detection methods that are "
     "characteristic of AI-generated text: Consistent formal structure throughout, "
     "limited variation in sentence length and phrasing, predictable word sequences and "
     "terminology placement, and uniformity in writing style and tone."),
    
    'Most of Your text is AI-Generated': 
    ("Our analysis detected strong and consistent patterns indicating AI generation "
     "across nearly all of the content. We found: Pervasive formal structure and "
     "consistent phrasing, minimal variation in writing style, "
     "predictable vocabulary and sentence patterns throughout, "
     "and multiple indicators aligned on AI-generated classification."),
    
    'Your text is AI-Generated': 
    ("Our analysis detected overwhelming evidence that this content was generated by an AI. "
     "All of our detection methods consistently identified AI-generation patterns: "
     "Pervasive consistent structure typical of language models, uniformity "
     "in word choice and phrasing throughout, predictable sequences matching AI baseline patterns, "
     "and no indicators of human-written variation or originality."),

     'Invalid Result':
     ("There is an error occurred in our system. This could be because either "
      "you have submitted invalid text or one of our signals is corrupted. "
      "Please report this issue on GitHub repository of this project.")
}