import os

class Config:
    """Application configuration."""
    DEBUG = os.getenv('DEBUG', False)
    RATELIMIT_ENABLED = True
    RATELIMIT_DEFAULT = '10 per minute'
    RATELIMIT_STORAGE_URL = 'memory://'
    MAX_CONTENT_LENGTH = 1024 * 1024
    
    CONFIDENCE_WEIGHTS = {
        'llm_judgment': 0.4,
        'stylometry': 0.35,
        'perplexity': 0.25,
    }
    
    CONFIDENCE_THRESHOLDS = [
        (0.00, 0.15, 'Your text is Human written'),
        (0.15, 0.30, 'Most of Your text is Human Written'),
        (0.30, 0.42, 'Your text is Most Likely Human written, may include parts generated by AI'),
        (0.42, 0.50, 'Your text is Likely Human written, may include parts generated by AI'),
        (0.50, 0.70, 'Your text contains mixed signals, with some parts generated by AI'),
        (0.70, 0.80, 'Your text is Likely AI-generated'),
        (0.80, 0.90, 'Your text is Most Likely AI-generated'),
        (0.90, 0.97, 'Most of Your text is AI-Generated'),
        (0.97, 1.00, 'Your text is AI-Generated'),
    ]
